### ISSUE TITLE
Does msal-react support to  sign-in users against private ADFS?

### ISSUE THREAD

**Issue by pwangsom** [Azure-Samples/ms-identity-javascript-react-tutorial#110]
# Issue

> Please provide us with the following information:

Does msal-react support to  sign-in users against private ADFS?

I have to develop a react web app that connects to my company ADFS for user sign-in
ADFS team could not support me on how to communicate between my react app and ADFS.

So I would like to know that can I apply this example code and msal-react library to ADFS?
Or there is another method for ADFS. Please suggest me.

Thank you.

## This issue is for the sample

```console
    - [ /] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ /] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@pwangsom msal-browser/msal-react supports ADFS 2019, please see this [doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/926f1c2ba0598575e23dfd8cdd8b79fa3a3d19ff/lib/msal-common/docs/ADFS.md). On principle the only difference is the `authority` string you pass to msal configuration. Unfortunately though, we don't have samples specifically targeting ADFS, but we would like to have some in future.
