### ISSUE TITLE
What is the preferred strategy for alternative implementations of PoP/passport?

### ISSUE THREAD

**Issue by rt-rkk** [Azure-Samples/ms-identity-javascript-react-tutorial#111]
An issue may not be the best way to go about finding this out, but the documentation leads to endless circles of potential options. The landing page for this sample clearly states:
This sample corresponds to an implementation of PoP without server nonce that is no longer recommended. If you start new projects don’t use this sample. The recommended approach will be documented in the future.

My problem is, there's no other recommendation listed. Any guidance would be greatly appreciated!

**Comment by derisen** [comment]
@rt-rkk Msal.js now supports requesting a PoP token with the server nonce parameter. See the [docs here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/shr-server-nonce.md). I'll prioritize updating the sample in this repo asap, though I'm afraid I don't have an ETA at the moment.
