### ISSUE TITLE
"prov_data" object breaking render

### ISSUE THREAD

**Issue by theOtherYonatan** [Azure-Samples/ms-identity-javascript-react-tutorial#161]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [x] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce
Follow the sample instructions all the way to the end.
>

### Any log messages given by the failure
Error raised in Chrome:
bundle.js:62221 Uncaught Error: Objects are not valid as a React child (found: object with keys {at, prov, altsecid}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (bundle.js:62221:13)
    at createChild (bundle.js:62470:11)
    at reconcileChildrenArray (bundle.js:62729:29)
    at reconcileChildFibers (bundle.js:63141:20)
    at reconcileChildren (bundle.js:66427:32)
    at updateHostComponent (bundle.js:67151:7)
    at beginWork (bundle.js:68789:18)
    at HTMLUnknownElement.callCallback (bundle.js:51421:18)
    at Object.invokeGuardedCallbackDev (bundle.js:51470:20)
    at invokeGuardedCallback (bundle.js:51532:35)
throwOnInvalidObjectType @ bundle.js:62221
createChild @ bundle.js:62470
reconcileChildrenArray @ bundle.js:62729
reconcileChildFibers @ bundle.js:63141
reconcileChildren @ bundle.js:66427
updateHostComponent @ bundle.js:67151
beginWork @ bundle.js:68789
callCallback @ bundle.js:51421
invokeGuardedCallbackDev @ bundle.js:51470
invokeGuardedCallback @ bundle.js:51532
beginWork$1 @ bundle.js:74545
performUnitOfWork @ bundle.js:73678
workLoopSync @ bundle.js:73591
renderRootSync @ bundle.js:73560
recoverFromConcurrentError @ bundle.js:72968
performConcurrentWorkOnRoot @ bundle.js:72869
workLoop @ bundle.js:121117
flushWork @ bundle.js:121091
performWorkUntilDeadline @ bundle.js:121375
bundle.js:65964 The above error occurred in the <td> component:

    at td
    at tr
    at tbody
    at table
    at div
    at http://localhost:3000/static/js/bundle.js:46805:5
    at div
    at div
    at IdTokenData (http://localhost:3000/static/js/bundle.js:804:98)
    at div
    at http://localhost:3000/static/js/bundle.js:43675:5
    at AuthenticatedTemplate (http://localhost:3000/static/js/bundle.js:26553:5)
    at Home (http://localhost:3000/static/js/bundle.js:2198:65)
    at Routes (http://localhost:3000/static/js/bundle.js:114743:5)
    at Pages
    at PageLayout (http://localhost:3000/static/js/bundle.js:1464:26)
    at MsalProvider (http://localhost:3000/static/js/bundle.js:26435:5)
    at Router (http://localhost:3000/static/js/bundle.js:114676:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:113485:5)
    at App (http://localhost:3000/static/js/bundle.js:79:5)
>

### Expected/desired behavior
Table with all the claims data
>

### Library version

>

### Browser and version

> Chrome

### Mention any other details that might be useful
File : @\1-call-api\SPA\src\components\DataDisplay.jsx
In the "IdTokenData" Component, in the tokenClaims array there is a an object that is different from all the other objects which is in array (= "arr") where arr[0] = 'prov_data' and arr[1] is an additional array which breaks the render at line 77.

 My Temporary solution: 
replace "tableRow" definition in lines 73-81 with this:
const tableRow = Object.keys(tokenClaims).map((key, index) => {
    return (
      <tr key={key}>
        {tokenClaims[key].map((claimItem) => {
          if (typeof claimItem !== 'string') return '';
          return <td key={claimItem}>{claimItem}</td>;
        })}
      </tr>
    );
  });

(added type check for the claimItem).
>

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Good catch; thanks for the feedback @theOtherYonatan will add this to the backlog.
