### ISSUE TITLE
Documentation not aligned in 3-Authorization-II/2-call-api-b2c/

### ISSUE THREAD

**Issue by JPardinas** [Azure-Samples/ms-identity-javascript-react-tutorial#19]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [x] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

> Follow exact steps to setup the two applications

### Any log messages given by the failure

> GET http://localhost:5000/hello 401 (Unauthorized)

### Expected/desired behavior

> GET http://localhost:5000/hello 200

### Library version

> 7fe2cc66f0da2fbbbe33784df4258a59f6512309

### Browser and version

> Chrome, Edge, Firefox, Safari

### Mention any other details that might be useful

> It's very nice to have this kind of samples but the readme is not aligned with the application configurations.

`API\config.json` 

- Documentation mention **tenantID** when the key is **tenantName**
- Documentation does not mention anything about the scopes defined in **protectedRoutes** when by default the value is **"demo.read"** when in the documentation the steps to follow creates **access_as_user** scope

`SPA\src\authConfig.js` 

- Documentation mention follow values like **Enter_the_Application_Id_Here** that does not exists.
- Documentation does not mention anything about **loginRequest** and **protectedResources**

**Comment by derisen** [comment]
@JPardinas thank you so much for spotting this! Will update the README asap (but feel free to make a PR if you like)
