### ISSUE TITLE
Sample app redirects to login even when logged in when using a b2c custom policy

### ISSUE THREAD

**Issue by vinmugambi** [Azure-Samples/ms-identity-javascript-react-tutorial#213]
# Sample app redirects to login even when logged in if using a b2c custom policy

As opposed to when using a flow, if you configure the SPA to use a custom policy , the app doesn't correctly authenticate users.  Users are redirected to https://{tenant-name}.b2clogin.com/{tenant-name}.onmicrosoft.com/oauth2/authresp?code={long-code}, which responds with a "400 - Bad Request", even after a successful login.

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [x] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

> Use the SignUpOrSignIn sample from https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/main/SocialAccounts

### Any log messages given by the failure

>

### Expected/desired behavior

> After signing in, one should be able to manage todo tasks. That's what happens when using a user flow.

### Library version

>

### Browser and version

> Chrome 107, Firefox 102 on Ubuntu

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@vinmugambi sorry for your trouble. Unless there is an issue with your MSAL configuration (which we don't know as you haven't shared your configuration), we are not able to offer help for issues that might stem from custom policy configuration. For that your best bet is to raise the issue in the [repo that has the policy you are using](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack). You can also raise [support ticket with B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/support-options).

That being said, see if you can get more information about the error you are receiving. Any errors in the browser console? Any error responses from the B2C service (check the network calls, in particular to the `/authorize` endpoint)

**Comment by vinmugambi** [comment]
@derisen. I don't think there is a problem in my config. The policy  either, I tested it  from the Azure portal. 

You can see working app when configured to use a user flow here: https://kind-mud-0b81d950f.2.azurestaticapps.net

Here are the changes I made to transition to the starter pack policy: https://github.com/vinmugambi/msal-react-sample/commit/33bc78e798cc13fa5dfb4aa9fe639c8cb00bc8dc

And here is how the app now behaves: https://wonderful-forest-013b5430f.2.azurestaticapps.net . It redirects continuously once you are logged in.

**Comment by derisen** [comment]
@vinmugambi I gave this a try (with policy): the app correctly signs-in the user and obtains a valid access token for the API, but the `/todolist` page is running into a loop that you mentioned, possibly because of SSO issues. It caught my attention that the `username` field in the account object is empty -`username` is a field that helps with SSO so it might be that `MsalAuthenticationTemplate` on that page is failing. Can you [follow this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-getaccountbyusername-returning-null-even-though-im-signed-in) to configure B2C to emit the `username` property (however these steps are for user-flows, you'll have to find out how to do the same with a custom policy)

**Comment by vinmugambi** [comment]
@derisen I added the email/username claim to the policy but the app still redirects. Still hosted at https://wonderful-forest-013b5430f.2.azurestaticapps.net/

**Comment by vinmugambi** [comment]
Figured it out. 
App.jsx is checking the TrustFrameworkPolicy claim  `tfp`   claim, the AD B2C starter-pack policies return it as `acr`

**Comment by derisen** [comment]
Aah, good catch! And that explains it. Will keep this open for now to update the sample to check for either `tfp` or `acr` claims (feel free to make a PR if you like)
