### ISSUE TITLE
After Edit profile Auth data not updated until login again in  ms-identity-javascript-react-tutorial project

### ISSUE THREAD

**Issue by harshilpatel8819** [Azure-Samples/ms-identity-javascript-react-tutorial#22]
After Edit profile Auth data not updated until login again in ms-identity-javascript-react-tutorial project

**Comment by harshilpatel8819** [comment]
https://www.loom.com/share/7785589ea5114b6caf0202b268bc0a7a

**Comment by derisen** [comment]
@harshilpatel8819 apologies for late response. I wasn't able to reproduce this with `1-Authentication/2-sign-in-b2c` sample. (See https://www.loom.com/share/2b9d18792f454c51adc969268b603779)

Can you tell me a bit more about your app settings? Which sample are you working on? What does your configuration file look like?
