### ISSUE TITLE
Configure AD APP redirect url with "api://xxxx" but page return AADSTS50011 ERROR.

### ISSUE THREAD

**Issue by HYLin0524** [Azure-Samples/ms-identity-javascript-react-tutorial#26]
# Issue

> I follow readme to register app and deploy react app on static web app.
The UI works, but when I click sign-in the popup window show the error message: 
```AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'xxxxxxx'.```
Why redirect url set with "api://...", rather than "http://"? 
Did I miss any step?

Thanks

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [x] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@HYLin0524 sounds like there's a mistake there. The redirect URI in the sample should be `http://localhost:3000`. The one that starts with `api://...` is not the redirect URI, it's the API scope that you use to acquire an access token. Can you share your configuration files (without the secret) to double check?

**Comment by HYLin0524** [comment]
@derisen my env setting here
```
REACT_APP_AAD_APP_CLIENT_ID=<my client id>
REACT_APP_AAD_APP_TENANT_ID=<my tenant id>
REACT_APP_AAD_APP_REDIRECT_URI=api://<my client id>
```

At step 4 in **configure-the-app-msal-react-spa-to-use-your-app-registration** section, it make me set REACT_APP_AAD_APP_REDIRECT_URI like `api://****-****-********-********/` the application id uri.
Also I checked the popup url parameter of redirect_url, it's shown like `api://****-****-********-********/`

Thanks

**Comment by HYLin0524** [comment]
@derisen 
I figure out the issue.
change `REACT_APP_AAD_APP_REDIRECT_URI=<my static web app url>`
neither `api://xxx` or `http://localhost`
![image](https://user-images.githubusercontent.com/19400339/133539304-666cda58-6b3b-4e12-bc30-1fa34cce60e8.png)

**Comment by derisen** [comment]
@HYLin0524 Aah, thanks for catching this! I'll get the **configure-the-app-msal-react-spa-to-use-your-app-registration** section fixed. Are you able to run your app now?

**Comment by HYLin0524** [comment]
@derisen Yes, my website works fine, thanks for your help.
