### ISSUE TITLE
ID token roles are not displayed

### ISSUE THREAD

**Issue by krisztianharagos** [Azure-Samples/ms-identity-javascript-react-tutorial#260]
# Issue

Am I right with the assumption that the ID token's roles claim is used for controlling display at the 5-1 sample? If so, what ensures that the ID token contains the roles and not only the access token?

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [x] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> Run the ps1 app registration script with an outlook.com account, run the application and sign in. Observe no "roles"-related row appear in the table.

### Any log messages given by the failure

> Nothing.

### Expected/desired behavior

> The roles claim should appear in the ID token - not just in the access token as per 
https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/c52878ae591fed751d6247927269d76dd6743886/5-AccessControl/1-call-api-roles/SPA/src/components/RouteGuard.jsx#L27

### Library version

>

### Browser and version

> Edge 110.0.1587.56

### Mention any other details that might be useful

> Also tried with a company tenant, the same. The difference is that the app registration there were manual.

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi @krisztianharagos,

Yes, if the id token contains the roles claim and the user is assigned to that role, you will be able to access different displays; for example, if the user has a `TaskAdmin` role, he will be able to read all the tasks in the API, but if the user has the role `TaskUser` they only can read and write their tasks.

If you do not see the roles claim, please ensure that you assign the application roles to the application and assign the user to the role. For more information, check the [following](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps). The roles should be [configured to all your tokens ](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps#usage-scenario-of-app-roles)once you add the users to the app role.

**Comment by krisztianharagos** [comment]
Hi @salman90,

Thank you for your message. I did the approles and assignments as well. I have used the Configure.ps1 script (for my outlook.com account) and also did it manually (within our firm). I have assigned myself the TaskAdmin role. It appears fine in the access token but the roles does not seem be appear in the ID token.

According to my understanding reading the sample code and also your linked documentation
_When the user authenticates with the app and requests an ID token to call the API, a roles claim is included in the ID token._
It should appear in the ID token as well, right?

**Comment by krisztianharagos** [comment]
Hey, 

Okay, the ID token contains the roles claim.
This is what misled me:
https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/utils/claimUtils.js#L11
together with
https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/utils/claimUtils.js#L186-L193

I think that could be fixed (basically commenting out line 11 and also doings something with the array's display, like JSON.stringify.

What do you think?

**Comment by salman90** [comment]
> Hi @salman90,
> 
> Thank you for your message. I did the approles and assignments as well. I have used the Configure.ps1 script (for my outlook.com account) and also did it manually (within our firm). I have assigned myself the TaskAdmin role. It appears fine in the access token but the roles does not seem be appear in the ID token.
> 
> According to my understanding reading the sample code and also your linked documentation _When the user authenticates with the app and requests an ID token to call the API, a roles claim is included in the ID token._ It should appear in the ID token as well, right?

When you Authenticate, you will get an id-token with the roles claim included in that id-token to be used in the SPA application only. When you request an access token to access the API, you will get an access token with the roles claim included in that token to access the API. You never send an id-token to access the API; it's always the access token.

**Comment by salman90** [comment]
> Hey,
> 
> Okay, the ID token contains the roles claim. The roles claim is just not being displayed in the table. This is what misled me: https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/utils/claimUtils.js#L11 together with https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/5-AccessControl/1-call-api-roles/SPA/src/utils/claimUtils.js#L186-L193
> 
> I think that could be fixed (basically commenting out line 11 and also doings something with the array's display, like JSON.stringify.
> 
> What do you think?

That is a good catch. I will add this as an enhancement to the sample. Thanks for the help!
