### ISSUE TITLE
Unclear file location in documentation

### ISSUE THREAD

**Issue by LeeRuns** [Azure-Samples/ms-identity-javascript-react-tutorial#264]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [x] 1-1) Sign-in with Azure AD
    - [x] 1-2) Sign-in with Azure AD B2C
    - [x] 2-1) Acquire a Token and call Microsoft Graph
    - [x] 3-1) Protect and call a web API on Azure AD
    - [x] 3-2) Protect and call a web API on Azure AD B2C
    - [x] 4-1) Deploy to Azure Storage and App Service
    - [x] 4-2) Deploy to Azure Static App Service
    - [x] 5-1) Call a web API using App Roles
    - [x] 5-2) Call a web API using Security Groups
    - [x] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [x] 6-3) Call a web API using Conditional Access Auth Context
    - [x] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

open the readme for any of these sample (ie https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/1-Authentication/2-sign-in-b2c/README.md#about-the-code)

### Any log messages given by the failure
There are no log messages for this ,but the problem is that when looking at all of the code "snippets" in the "About The Code" section, there are no file names.  The setup for the project has a lot of msal cutom files, and I can't seem to resolve where each of these snippets is in the actual code, or if they just don't exist and i need to add them.  This would really help for clarity.  A key example is that when i look at the initial project for B2C sign in (1-Authentication/b2c....), there is a function APP() for sso, but I have no idea where that is or if i need to make a whole new file for it., an example is this snipped
```
```
if i want to add the SSO feature then where do i stick this section of code? Or is it already present somewhere and the "About the Code" section is providing extra explanation?  If it is extra explanation then please site where it is. 

Just feeling a bit lost going through thispart of the readme.  Otherwise I have found it to be very helpful.

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi @LeeRuns, Thanks for flagging this and for taking the time to give us your feedback. I will communicate your feedback with our documentation team, and we will address this as soon as possible.
