### ISSUE TITLE
Missing the Call API button

### ISSUE THREAD

**Issue by oliver-tbs** [Azure-Samples/ms-identity-javascript-react-tutorial#266]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [x] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

> Follow all steps in tutorial up to **Explore the sample**

### Any log messages given by the failure

> n/a

### Expected/desired behavior

> Once you authenticate, Select the Call API button on the navigation bar. -- **I do not see the Call API button, on screen or in code**

### Library version

> main

### Browser and version

> Edge

### Mention any other details that might be useful

> Is this because I am not authenticated? I don't get any errors or other indication that this is the case.

Thanks! We'll be in touch soon.

**Comment by oliver-tbs** [comment]
I figured out a couple of things that now has this working for me...

1. The button is actually named "Profile"
2. I had to modify this line of code in Profile.jsx (line 54 for me):
before: .then((response) => setGraphData(response.value))
after: .then((response) => setGraphData(response))

**Comment by salman90** [comment]
@oliver-tbs Thanks for pointing this out and providing the solution. I will update this right away.
