### ISSUE TITLE
Export module for App.jsx is throwing TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by blackadi** [Azure-Samples/ms-identity-javascript-react-tutorial#27]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ x ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a

```console
    - [ x ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> When running the sample after following described steps [here](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/2-Authorization-I/1-call-graph/README.md)

### Any log messages given by the failure

>After running the sample via npm start command, the following error will be thrown -> TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

![image](https://user-images.githubusercontent.com/16793335/134153253-9bf0e983-63d2-43c0-b93e-44799cd29c26.png)

### Expected/desired behavior

> To run the sample successfully. 

### Library version

> "dependencies": {
    "@azure/msal-browser": "^2.16.0",
    "@azure/msal-react": "^1.0.1",
    "@microsoft/microsoft-graph-client": "^2.2.1",
    "bootstrap": "^4.5.3",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1",
    "react": "^17.0.0",
    "react-bootstrap": "^1.3.0",
    "react-dom": "^17.0.0",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "react-scripts": "4.0.1"
  },

### Browser and version

> Chrome, Edge, Firefox, Safari? 
All

### Mention any other details that might be useful

> The above sample will work as expected when changing the `App.jsx` export module from `module.exports = App` to this `export default App;` 

![image](https://user-images.githubusercontent.com/16793335/134154281-8caf5f49-c948-49ce-835f-7e4fbab6ea00.png)
![image](https://user-images.githubusercontent.com/16793335/134154323-9fd07159-c246-4d2d-ad30-85e6908481a9.png)

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@blackadi thanks for catching this! It was supposed to be `export default App`, my mistake. Fixing in a PR asap.

**Comment by derisen** [comment]
This has been fixed. Closing.
