### ISSUE TITLE
[Question] What is the reason to perform mapping with the storage in the database for the ARCS claim demo?

### ISSUE THREAD

**Issue by ievgennaida** [Azure-Samples/ms-identity-javascript-react-tutorial#287]
# Question
For the provided demo "3-call-api-acrs" user needs to configure mapping between the operation and Auth context manually and store them into the DB.

1. Is there is any reason to make this mapping 'dynamic' by requesting the avaliable contexts from the azure identity provider?
I exactly know which endpoints should be protected can we just check context in the acrs claim in the similar way like it's done for the roles access?

2. Is it supported for B2C?  

See reference here:
https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/6-AdvancedScenarios/3-call-api-acrs/README.md

Will appreciate an answer.

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [x] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [x] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [x ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [x] question
    - [ ] feature request
    - [ ] documentation issue or request
```

**Comment by salman90** [comment]
Hi [ievgennaida](https://github.com/ievgennaida)

We recommend that you dynamically check if the auth contexts exist in the tenant before protecting your endpoint, even if you have them on hand in case any update happens to them by any user in the tenant.

Unfortunately, auth context is not supported in B2C tenants.

**Comment by ievgennaida** [comment]
@salman90 Thanks for the answer.
I had this question mainly for the scenario that I would like to enforce MFA before the operation in b2c.
While ARCS claim is not supported I think about the next approach:
Create two login policies and two claims
1. 'Data access' claim and "SUSI policy 1". 
2. 'Protected access' claim and another "SUSI policy 2".
- User will log in to the SPA application with claim 'Data access' and 'SUSI policy 1' and will work normally.
- Before the sensitive call to the API Frontend will call new login with 'Protected access' claim before the 'sensitive call' with a new 'SUSI policy 2' where MFA is enforced.  
- Backend API (resource server) Should check for the normal calls 'Data access' and 'SUSI policy 1'  and for the 'sensetive calls'  'Protected access' and that 'SUSI policy 2' were used.

I would appreciate and overview whether this idea can simulate auth context for the  B2C tenants.

**Comment by derisen** [comment]
@ievgennaida this approach makes sense to me. Each policy acquires its own tokens (reflected in the iss claim), and so you can load the SUSI policy 2 to acquire a token for your backend API and then configure your backend API to only authorize tokens issued to your SUSI policy 2 (see [claims validation](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens#claims-based-authorization)).
