### ISSUE TITLE
"Pre-registered application" is either non-existent or inadequately documented

### ISSUE THREAD

**Issue by shearichard-nec** [Azure-Samples/ms-identity-javascript-react-tutorial#289]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [x] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
    - [ ] 6-4) Sign-in with Hybrid SPA flow
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [x] documentation issue or request
```

### Minimal steps to reproduce

Follow the instructions in https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/1-Authentication/2-sign-in-b2c/README.md to **Step 3** and then, as suggested in the text, skip to https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/1-Authentication/2-sign-in-b2c/README.md#step-4-running-the-sample .

In **Step 3** the text "This sample comes with a pre-registered application for demo purposes. " appears but I can't find any indication of how this is meant to be running and when I follow the instructions within **Step 4** under "[Explore the sample](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/1-Authentication/2-sign-in-b2c/README.md#explore-the-sample)" , specifically using "Sign-in using Popup" the popup launches but the text within the popup reads "Firefox can’t establish a connection to the server at localhost:6420".

### Any log messages given by the failure

"Firefox can’t establish a connection to the server at localhost:6420".

### Expected/desired behavior

One of the following 

 - The text at **Step 3** should be removed because there is no such app or
 - The location and use of the "pre-registered application" should be better documented within this README

### Library version

Don't know where to find this information, I cloned the repo today the latest commit was #8ca0fb0

### Browser and version

Firefox 111 (Firefox for Ubuntu)

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@shearichard-nec apologies for the late response -and thanks for catching this! Indeed the redirect uri was not registered correctly. I've made a PR to update the samples with a new app registration, so please give this a try again and let us know if you are still having issues.
