### ISSUE TITLE
Error in sample documentation?

### ISSUE THREAD

**Issue by emaborsa** [Azure-Samples/ms-identity-javascript-react-tutorial#3]
I am trying to setup a SinglePageApplication following [this tutorial](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/2-call-api-b2c), taken from [this page](https://docs.microsoft.com/it-it/azure/active-directory/develop/sample-v2-code).
At [point 7](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/2-call-api-b2c#register-the-spa-app-msal-react-spa) I find:
_Select the Add a permission button and then:
Ensure that the Microsoft APIs tab is selected.
In the Commonly used Microsoft APIs section, select Microsoft Graph
**In the Delegated permissions section, select the User.Read in the list. Use the search box if necessary.**
Select the Add permissions button at the bottom._

Can't do it:
![azure_delegate_permission](https://user-images.githubusercontent.com/9129912/112204747-51877b00-8c14-11eb-8e55-8dc3e445ac9d.png)

How do I proceed? Skipping this permission I get 401 once I call the _HelloApi_.

**Comment by derisen** [comment]
@emaborsa sorry, that seems to be incorrect. Please ignore that ("user.read") and only add the permissions for your web API. I'll remove that part ASAP.

**Comment by emaborsa** [comment]
@derisen thanks for your quick answer. 
The Spa is working, I am able to login. However, when i click on HelloAPI I get a 401. In the developer tools I see the request to get the token (200), the preflight OPTIONS (200), but then the effective call to hello with 401. In the headers I see _WWW-Authenticate: token is not found_.

**Comment by derisen** [comment]
@emaborsa no worries. Can you please share the content of your configuration files, for both SPA and web API?

**Comment by emaborsa** [comment]
At the end I got it to work, The key was to set _cacheLocation_ to _localStorage_.
