### ISSUE TITLE
How to renew auth token in Reactjs App with Azure AD B2C

### ISSUE THREAD

**Issue by priyadarshiniMuthuraman** [Azure-Samples/ms-identity-javascript-react-tutorial#43]
Hi,

Am using Azure AD B2C authentication for my Reactjs App, I have integrated it the login and logout process is working fine and obtaining a AUTH token to secure web API's. The  issue is that, how to renew the AUTH token based on Refresh token in react app with AD B2C.

**Comment by priyadarshiniMuthuraman** [comment]
Any idea on the above process?

**Comment by salman90** [comment]
Hi @priyadarshiniMuthuraman 
Sorry for the late response. MSAL handles refreshing the token for you. If the access token is expired but the refresh token is still valid, MSAL will use the given refresh token to retrieve a new set of tokens. Please check the [token renewal ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal)section for more information.
