### ISSUE TITLE
Error Clients must send a client_secret when redeeming a confidential grant.

### ISSUE THREAD

**Issue by seamy20** [Azure-Samples/ms-identity-javascript-react-tutorial#44]
# INvalid request undefined - Error Clients must send a client_secret when redeeming a confidential grant.

> Please provide us with the following information:

## This issue is for the sample

I have configured the details and get the azure login page displayed but when I log in as a user i get an error returned Error Clients must send a client_secret when redeeming a confidential grant.

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [X] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [X] documentation issue or request
```

### Minimal steps to reproduce

>configure  authConfig and run npm install and npm start

### Any log messages given by the failure

×
invalid_request: undefined - [undefined]: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.
Correlation ID: 74c80c57-6761-4eff-8b8a-bf3b728117b0
Timestamp: 2022-02-11 15:13:03Z
 - Correlation ID: undefined - Trace ID: undefined

### Expected/desired behavior

Redirect after login

### Library version

>

### Browser and version

> Chrome,Edge

### Mention any other details that might be useful

>Azure is setup correctly as a different app uses this login featuer but i am trying to configure this to work with a React Js App

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi [seamy20](https://github.com/seamy20) , Please make sure that you configured your app as a single-page application in azure active directly. Under Manage, select Authentication > Add a platform make sure to the selected signal page application. For more details, please follow this [link](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow).
