### ISSUE TITLE
In react-router 6 Switch has been removed and using Route would give a Runtime error as "Route child should be

### ISSUE THREAD

**Issue by mkokabi** [Azure-Samples/ms-identity-javascript-react-tutorial#57]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [x] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

Upgrade react-router-dom to ^6.0.2

### Any log messages given by the failure

Attempted import error: 'Switch' is not exported from 'react-router-dom'.

### Expected/desired behavior

Working with Routes

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by mkokabi** [comment]
If I try replacing Switch with Routes, at run-time it would give:
Error: [RouteGuard] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

**Comment by salman90** [comment]
Hi @mkokabi , thanks for reaching out. The sample supports React Router version 5, and that's why you're getting the error in version 6, but If you want to migrate from React Router version 5  to version 6, please take a look at the React  Router [documentation](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6).

**Comment by mkokabi** [comment]
Hi @salman90 ,
I know how to upgrade from Router version 5 to 6 but the issue is the architecture of this project is based on creating a RouteGuard class and using it instead of Route and in version 6 this is not supported. The error in version 6 is clearly saying all children of Routes **must** be a Route or React.Fragment.

**Comment by salman90** [comment]
@mkokabi Thanks for the feedback and clarification. I added your request to support react-router version 6 in the samples that use the RouteGuard class to our backlog, and we will update the samples as soon as possible.
