### ISSUE TITLE
Body must include client_secret or client_assertion

### ISSUE THREAD

**Issue by rylincoln** [Azure-Samples/ms-identity-javascript-react-tutorial#6]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone the repository and follow the instructions for 3-Authorization-II/1-call-api

### Any log messages given by the failure
> `AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.Trace ID: 702e16ef-2f43-43f6-b52c-363030d61102Correlation ID: be8f545a-df36-4283-83d7-145531655fa0Timestamp: 2021-05-03 19:38:57Z`

### Expected/desired behavior
> Expected to be able to login and call the local API protected by azure ad.

### Browser and version?
> Firefox 88.0

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@rylincoln can you please double check if the app registered as a **single-page application**:

![ss1](https://user-images.githubusercontent.com/13197548/116927515-9e497300-ac10-11eb-9be5-5df58b304294.png)

**Comment by rylincoln** [comment]
doh! I totally missed that - thanks that is the problem.
