### ISSUE TITLE
PoP Authentication Issues ( Cannot generate a POP jwt if the token_claims are not populated ) - not working 

### ISSUE THREAD

**Issue by bindu07** [Azure-Samples/ms-identity-javascript-react-tutorial#64]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Deploy to Azure Storage and App Service
    - [ ] 4-2) Deploy to Azure Static App Service
    - [ ] 5-1) Call a web API using App Roles
    - [ ] 5-2) Call a web API using Security Groups
    - [ ] 6-1) Call Microsoft Graph using on-behalf-of flow
    - [ ] 6-2) Call a web API using Proof of Possession tokens
    - [ ] 6-3) Call a web API using Conditional Access Auth Context
```

## This issue is for a 

6-2) call a web API using PoP tokens 

```console
    - [ ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

> I have changed the authconfig files to my azure client id and tenant id 

### Any log messages given by the failure

>{"eventType":"msal:loginFailure","interactionType":"redirect","payload":null,"error":{"errorCode":"token_claims_cnf_required_for_signedjwt","errorMessage":"Cannot generate a POP jwt if the token_claims are not populated","subError":"","name":"ClientAuthError"},"timestamp":1648618526405}

### Expected/desired behavior

> Token by the azure/ redirect to the webpage authenticating my account and add the tasks as mentioned

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

Chrome - 98.0 and firefox 99

### Mention any other details that might be useful

> I got the 1 working (Recat SPA Authentication successfully)

![Github_AZURE](https://user-images.githubusercontent.com/17426318/160759300-bc0df5f4-2851-42e4-832d-6e426b896220.png)

**Comment by salman90** [comment]
Hi @bindu07 , We don't recommend using the POP sample due to some implementation issues. For more information check the [README](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/6-AdvancedScenarios/2-call-api-pop)
