### ISSUE TITLE
401 Error in /hello API when I click on HelloAPI tab

### ISSUE THREAD

**Issue by Tushar-Beladiya** [Azure-Samples/ms-identity-javascript-react-tutorial#7]
@derisen 
I am getting access token and also able to run GraphAPI but I /hello API not executed and thought the 401 error with "Unauthorized" message in the network tab

![image](https://user-images.githubusercontent.com/16912314/117119592-ee127080-adaf-11eb-8db1-98723b09f181.png)

I have given the API permission like User.Read and also try without that permission but although I am getting the same error (401)

How can I solve this issue?

Thanks!

**Comment by derisen** [comment]
@Tushar-Beladiya there's not enough info to troubleshoot this, could you please fill out the issue template? Importantly, specify which sample you're having trouble with, and share your auth params & configuration (masking any secrets).

**Comment by Tushar-Beladiya** [comment]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

### Any log messages given by the failure
> console.log error message: SyntaxError: Unexpected token U in JSON at position 0
**Error In the Network Tab**: API status code: 401
**message**: Unauthorized

### Expected/desired behavior
> Should call /hello API successfully

### Browser and version?
> Google Chrome (Version 90.0.4430.93 (Official Build) (64-bit)


### Versions
> NodeJs Versions: 14.16.0

### Sample Used By
> I am using the following sample code:
   https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api

### Mention any other details that might be useful
I am getting access token and also able to run GraphAPI but I /hello API not executed and thought the 401 error with "Unauthorized" message in the network tab

I am putting the CURL request here of /hello API so you can get auth param or anything:
curl "http://localhost:5000/hello" ^
  -H "Connection: keep-alive" ^
  -H "authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJhcGk6Ly9iZGUxMjk0OS1kYmZhLTQyYWQtOWNmMC01MWZkN2I3MWNmMjciLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81NWIxNWQ1ZS1hYmY1LTQ2NDItYThhNi04ZmM3MzY3MWFlYWUvIiwiaWF0IjoxNjIwMzg5MDEyLCJuYmYiOjE2MjAzODkwMTIsImV4cCI6MTYyMDM5MjkxMiwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhUQUFBQUExazkzZzRWNGFpSFRnZDB4ZW9SYVpPSDRHNTk5ajZuZ2ExMEVGYTdRTWZQUHpRUjIyeWc1Uk9NdE9JaituTU8iLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiNDgwYjgyNWUtNGZlMy00MGYwLWE3YjEtMzJlM2VjZWU5YTY0IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJCZWxhZGl5YSIsImdpdmVuX25hbWUiOiJUdXNoYXIiLCJpcGFkZHIiOiIyMTkuOTEuMjQ1LjE4MCIsIm5hbWUiOiJUdXNoYXIgQmVsYWRpeWEiLCJvaWQiOiJhNmZmNWNlOC03YTYyLTQwMDEtODc5MS1lYzAyNzRkMWEzOGIiLCJyaCI6IjAuQVhnQVhsMnhWZldyUWthb3BvX0hObkd1cmw2Q0MwampUX0JBcDdFeTQtenVtbVI0QUY4LiIsInNjcCI6ImFjY2Vzc19hc191c2VyIiwic3ViIjoiYlNGTElIQ2k0UW9na3gxbXlxLXVwZ0JSOUtDa2dCQkJ5cmJYRnJlbjQ1VSIsInRpZCI6IjU1YjE1ZDVlLWFiZjUtNDY0Mi1hOGE2LThmYzczNjcxYWVhZSIsInVuaXF1ZV9uYW1lIjoidGJATTM2NUVEVTIyODQzMy5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJ0YkBNMzY1RURVMjI4NDMzLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6IjBpeTBpallKczB1T2ZLOXZGQkUzQUEiLCJ2ZXIiOiIxLjAifQ.gPy0GjLQw-QAID9NlXgTaAoI3_W87qiwxKM3YQpmofawQMS0pO98k7q8Myi7GaCt4BAV4ss0eeEvE2gawdnpXj6rRIG43Ap_P64CIsBtVO9E3RoywCAXr2GF6OZPeAcvVcclOjtfLOIKGMFTWZ4-ER0egltaPbj3STznMCMC9yix7bVYAKgnJhG0tI0IHrVE9onZM6AKInmaY6etxEuEnl6xW0NIBfBavkpImCsdTy1YZ1kIkU48UvFoMoyXe3x8Ywz8EQgnlPvlEDrwroD9hntyEcBld72wr6yPclqlWsM1OY9nbfF07ZGUyKKGvRa2yFvUpVMKezXRU75aAlLQUg" ^
  -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" ^
  -H "Accept: */*" ^
  -H "Sec-GPC: 1" ^
  -H "Origin: http://localhost:3000" ^
  -H "Sec-Fetch-Site: same-site" ^
  -H "Sec-Fetch-Mode: cors" ^
  -H "Sec-Fetch-Dest: empty" ^
  -H "Referer: http://localhost:3000/" ^
  -H "Accept-Language: en-US,en;q=0.9" ^
  --compressed

> ---------------------------------------------------------------
> Thanks!

**Comment by derisen** [comment]
@Tushar-Beladiya do you see any errors in the console of the web API? It is possible that the issue is with the version of the access token. Can you do this.

1. Navigate to Azure portal > App Registration > [Web API Registration] > Manifest
2. Set `accessTokenAcceptedVersion` property to **2**.

and then give this a try again?

**Comment by Tushar-Beladiya** [comment]
@derisen I can see the error in chrome browser (GET http://localhost:5000/hello 401 (Unauthorized)

And I have set the accessTokenAcceptedVersion property to 2 but same error is occure

**Comment by derisen** [comment]
@Tushar-Beladiya not the chrome browser console. Check the terminal window where you run the web API project:

In `API/index.js`, modify the options as shown below (add the `loggingNoPII` property):

```javascript
const options = {
    identityMetadata: `https://${config.metadata.authority}/${config.credentials.tenantID}/${config.metadata.version}/${config.metadata.discovery}`,
    issuer: `https://${config.metadata.authority}/${config.credentials.tenantID}/${config.metadata.version}`,
    clientID: config.credentials.clientID,
    audience: config.credentials.clientID, // audience is this application
    validateIssuer: config.settings.validateIssuer,
    passReqToCallback: config.settings.passReqToCallback,
    loggingLevel: config.settings.loggingLevel,
    scope: config.protectedRoutes.hello.scopes,
    loggingNoPII: false
};
```

Then run the API and watch the console when you make a call to the API. It should display the validation process.

If this won't help either, then can you send me the network trace, using [Fiddler](https://www.telerik.com/fiddler). You can send it to my email, which is on my GitHub profile page.

**Comment by Tushar-Beladiya** [comment]
@derisen You can find my repo here: https://github.com/Tushar-Beladiya/1-call-api

**Comment by derisen** [comment]
@Tushar-Beladiya I've just cloned your repository and registered new apps following the [instructions](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api#registration). However I did not run into your issue -everything seems to work as expected.

Are you running the apps behind a proxy or a firewall by chance? To be honest I'm not sure if that would cause your issue, but I'm puzzled what's going wrong here. Sorry to ask this, but can you update your msal packages to the latest, register apps from stratch and give it a try again?

Also a small comment, in your [config.json](https://github.com/Tushar-Beladiya/1-call-api/blob/3ad11f46f746a809d44a88818a51b93415230165/API/config.json#L19), scopes should be just "access_as_user" as opposed to "api://<clientID>/access_as_user".

**Comment by Tushar-Beladiya** [comment]
The issue has been solved

Thanks@derisen
